In [58]:
import numpy as np


In [8]:
import numpy as np

a = np.array([[1, 2, 4], [1, 3, 5]])
a2 = a.view()   #shallow copy
a3 = a.copy()   #deep copy

a2[0][1] = 111
display(a)

a3[0][1] = 101
display(a)

array([[  1, 111,   4],
       [  1,   3,   5]])

array([[  1, 111,   4],
       [  1,   3,   5]])

In [2]:
import numpy as np

list = [1, 3, 5]
a1 = np.array(list)

a2 = np.array([2, 4, 6])
a3 = np.array(range(1, 11))

a4 = np.array((7, 11, 101, 555))

a5 = np.array([3 * x for x in range(1, 6)])

print(a1, a2, a3, a4, a5, sep='\n\n')

[1 3 5]

[2.  4.  6.3]

[ 1  2  3  4  5  6  7  8  9 10]

[  7  11 101 555]

[ 3  6  9 12 15]


In [2]:
import numpy as np

a = np.array([1, 2.5, 0])

b = np.array([1, True, 'Three', 4.5])

c = np.array([False, True, 10])

print(a, b, c, sep='\n\n')

#print(a.dtype, b.dtype, c.dtype, sep='\n')

[1.  2.5 0. ]

['1' 'True' 'Three' '4.5']

[ 0  1 10]


In [57]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

b = np.array([1.2, 3.141, 5.55, 9.99], dtype='i')

c = np.array([-5, -1, 0, 1, 1.5, 10], dtype=np.bool)

print(a, b, c, sep='\n\n')

[1. 2. 3. 4. 5.]

[1 3 5 9]

[ True  True False  True  True  True]


In [62]:
import numpy as np

a = np.array([1, True, 'Three'], dtype=int)
a

ValueError: invalid literal for int() with base 10: 'Three'

In [71]:
import numpy as np

a = np.array([1.2, 3.141, 5.55, 7.11])
a2 = a.astype(int)

b = np.array([7, 11, 101, 555])
b2 = b.astype('f')

print(a2, b2, sep='\n\n')

[1 3 5 7]

[  7.  11. 101. 555.]


In [82]:
import numpy as np

z = np.zeros(5)
zi = np.zeros(5, dtype=int)

o = np.ones(5)
oi = np.ones(5, dtype=int)

f1 = np.full(5, 10)
f2 = np.full(5, 1.5)
f3 = np.full(5, 2.5, dtype=int)


print(z, zi, o, oi, f1, f2, f3, sep='\n\n')

[0. 0. 0. 0. 0.]

[0 0 0 0 0]

[1. 1. 1. 1. 1.]

[1 1 1 1 1]

[10 10 10 10 10]

[1.5 1.5 1.5 1.5 1.5]

[2 2 2 2 2]


In [125]:
import numpy as np

a = np.arange(1, 10)
b = np.arange(1, 10, 2)
c = np.arange(1, 10, 2.5)
d = np.arange(10, 1, -3)
e = np.arange(-10.5, 5.5, 3.5)
f = np.arange(100, 1, 10)

print(a, b, c, d, e, f, sep='\n\n')

[1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]

[1.  3.5 6.  8.5]

[10  7  4]

[-10.5  -7.   -3.5   0.    3.5]

[]


In [123]:
import numpy as np

a1 = np.linspace(1, 10, 4)
a2 = np.linspace(1, 10, 6)
a3 = np.linspace(1, 10, 4, dtype=int)
a4 = np.linspace(-10, 10, 6)
a5 = np.linspace(10.5, 1.5, 5)

print(a1, a2, a3, a4, a5, sep='\n\n')

[ 1.  4.  7. 10.]

[ 1.   2.8  4.6  6.4  8.2 10. ]

[ 1  4  7 10]

[-10.  -6.  -2.   2.   6.  10.]

[10.5   8.25  6.    3.75  1.5 ]


In [21]:
import numpy as np

a = np.random.randint(10, 100, 10)  
b = np.random.randint(1, 11, 10)
c = np.random.randint(-10, 5, 10)

print(a, b, c, sep='\n\n')

[84 10 52 92 15 32 94 62 32 54]

[ 8 10  9  1 10  1  3  7  5  9]

[-3  0  4 -3 -8  2  0  4 -1  0]


In [77]:
import numpy as np

a = np.random.uniform(10, 100, 10)  
b = np.random.uniform(1, 11, 10)
c = np.random.uniform(-10, 5, 10)

print(a, b, c, sep='\n\n')

[24.19922663 45.00759783 56.37165861 78.1849762  78.79225503 81.60495672
 22.1157477  31.23153399 61.05413606 39.97717941]

[ 9.93422234  4.94941905  3.55124965  5.79786114  2.87066466 10.09241789
  4.37498805  4.27783103  7.38313702  6.35633319]

[ 2.12163507  2.17016099 -5.96939057  2.25265925 -5.82338241 -2.24977531
  2.02252299 -1.3321545  -7.64202545 -1.09522574]


In [230]:
import numpy as np

a = np.random.rand(10)
b = np.random.choice([7, 11, 101, 108, 1009, 555], 10)
c = np.random.choice((-10, -2.5, 0, 1, 3.141, 5), 7)

print(a, b, c, sep='\n\n')

[0.69010545 0.26389235 0.50765557 0.03477166 0.8943677  0.5120075
 0.20516458 0.41520263 0.96171054 0.1225382 ]

[   7  101    7  108  555 1009  108 1009  108   11]

[ 3.141 -2.5    3.141  5.     1.    -2.5    1.   ]


In [7]:
import numpy as np

arr = np.array([7, 11, 108, 1009, 101, 555])

for value in arr:
    print(value)

print()

for (index, value) in enumerate(arr):
    print(f'{index}: {value}')

7
11
108
1009
101
555

0: 7
1: 11
2: 108
3: 1009
4: 101
5: 555


In [34]:
import numpy as np

arr = np.array([2, 7, 11, 101, 108, 360, 404, 555, 747, 1009, 2020])
print(
    arr[5:],
    arr[3:9],
    arr[1:10:2],
    arr[10:1:-2],
    arr[1:1000:3],
    sep='\n\n')

[ 360  404  555  747 1009 2020]

[101 108 360 404 555 747]

[   7  101  360  555 1009]

[2020  747  404  108   11]

[   7  108  555 2020]


In [30]:
import numpy as np

arr = np.array([2, 7, 11, 101, 108, 360, 404, 555, 747, 1009, 2020])
print(
    arr[-5:],
    arr[-9:-3],
    arr[-10:-1:2],
    arr[-5:10],
    arr[3:-3],
    sep='\n\n')

[ 404  555  747 1009 2020]

[ 11 101 108 360 404 555]

[   7  101  360  555 1009]

[ 404  555  747 1009]

[101 108 360 404 555]


In [46]:
import numpy as np

arr = np.array([2, 7, 11, 101, 108, 360, 404, 555, 747, 1009, 2020])

idx = [0, 2, 4, 8]
a = arr[idx]

idx2 = np.array([-1, -5, -7, -10, -3])
b = arr[idx2]

c  = arr[[7, 3, 9, 1]]

print(a, b, c, sep='\n\n')

[  2  11 108 747]

[2020  404  108    7  747]

[ 555  101 1009    7]


In [48]:
import numpy as np

arr = np.random.randint(10, 101, 10)

a = arr[0] ** 2
b = arr[:5] / 2
c = arr[1::2] * 5
d = arr[[0, 2, 4, 8]] - arr[[1, 5, 7, 9]]

print(arr, a, b, c, d, sep='\n\n')

[38 39 32 91 58 36 40 25 38 32]

1444

[19.  19.5 16.  45.5 29. ]

[195 455 180 125 160]

[-1 -4 33  6]


In [72]:
import numpy as np

arr = np.random.randint(10, 101, 10)

a = arr[arr >= 50]

b = arr[arr % 2 == 0]

c = arr[(arr > 20) & (arr < 60)]

d = arr[(arr != 33) | (arr != 51) | (arr != 89)]

print(arr, a, b, c, d, sep='\n\n')

[100  35  17  26  35  31  84  34  24  78]

[100  84  78]

[100  26  84  34  24  78]

[35 26 35 31 34 24]

[100  35  17  26  35  31  84  34  24  78]


In [6]:
import numpy as np

a0 = np.zeros([3, 4], dtype=int)
a1 = np.ones([4, 6], dtype=int)
af = np.full((4, 4), 10)

print(a0, a1, af, sep='\n\n')

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [7]:
import numpy as np

rand_int = np.random.randint(10, 101, [5, 5])
uniform = np.random.uniform(1, 11, (4, 5))
rand = np.random.rand(6, 5)
choice = np.random.choice([3.141, 0.357, -10, 9.99, 33, -2.57], 
                          (3, 4))

print(rand_int, uniform, rand, choice, sep='\n\n')

[[81 31 77 24 91]
 [60 62 66 12 68]
 [98 53 27 57 84]
 [20 86 82 95 38]
 [31 24 94 61 26]]

[[ 7.07105254  5.8015191   7.15388813  7.75315294 10.82119377]
 [ 6.32012535  7.52073085 10.4744276   7.10430196  8.85715928]
 [ 4.42065821 10.14763457  8.68297172  6.41645912  3.70392707]
 [ 7.99033588  2.63289794  1.61727172  3.44699341  6.74173441]]

[[0.09797336 0.73983085 0.99289844 0.03756859 0.06547928]
 [0.90778141 0.5606727  0.82222163 0.98642227 0.39381183]
 [0.7632872  0.84030859 0.75229086 0.53871129 0.62038308]
 [0.20687485 0.76428563 0.35953861 0.8148218  0.22101333]
 [0.03694924 0.83149091 0.86537093 0.85587959 0.57091115]
 [0.57736582 0.80869615 0.22346713 0.11388408 0.74883938]]

[[ -2.57   33.     -2.57    0.357]
 [  3.141 -10.     33.    -10.   ]
 [  0.357   3.141   3.141   0.357]]


In [20]:
import numpy as np

arr1 = np.random.randint(10, 101, [4, 3])
arr2 = arr1.reshape(3, 4)

print(arr1, arr2, sep='\n\n')

arr2 *= 2

print()
print(arr1, arr2, sep='\n\n')

[[ 21 100  43]
 [ 29  38  79]
 [ 69  97  28]
 [ 60  53  89]]

[[ 21 100  43  29]
 [ 38  79  69  97]
 [ 28  60  53  89]]

[[ 42 200  86]
 [ 58  76 158]
 [138 194  56]
 [120 106 178]]

[[ 42 200  86  58]
 [ 76 158 138 194]
 [ 56 120 106 178]]


In [11]:
import numpy as np

a = np.random.randint(1, 11, [3, 4])

print(a,
      a[0, 0],
      a[1, 3],
      a[2, 2],
      sep='\n\n')

[[10  7  4  9]
 [ 7  9  2  5]
 [ 6  8  7  4]]

10

5

7


In [36]:
import numpy as np

a = np.random.randint(1, 11, [3, 4])
b = np.random.choice([10, 20, 30], [3, 4])

print(a, 
      a + 10, 
      b, 
      a * b, 
      sep='\n\n')

[[ 9  6  8  4]
 [ 7  8 10  9]
 [ 2  4  6  6]]

[[19 16 18 14]
 [17 18 20 19]
 [12 14 16 16]]

[[20 30 10 20]
 [30 20 30 20]
 [20 30 20 30]]

[[180 180  80  80]
 [210 160 300 180]
 [ 40 120 120 180]]


In [27]:
import numpy as np

a = np.random.randint(1, 11, [6, 6])
print(a,
      a[1:5, 2:4],
      a[:4, 2:],
      a[::, :6:2],
      sep='\n\n')


[[ 2  3  7  1  4  8]
 [ 2  4  6  7  8  2]
 [ 8  9  7  3 10  6]
 [ 8 10  4  7  6  8]
 [ 3  4  9  7  1  2]
 [ 1  3  2 10  4  9]]

[[6 7]
 [7 3]
 [4 7]
 [9 7]]

[[ 7  1  4  8]
 [ 6  7  8  2]
 [ 7  3 10  6]
 [ 4  7  6  8]]

[[ 2  7  4]
 [ 2  6  8]
 [ 8  7 10]
 [ 8  4  6]
 [ 3  9  1]
 [ 1  2  4]]


In [36]:
import numpy as np

arr = np.random.randint(10, 101, [4, 4])

a = arr[arr >= 80]
b = arr[arr % 2 == 0]
c = arr[(arr >= 0) & (arr < 60)]

print(arr, a, b, c, sep='\n\n')

[[75 50 18 42]
 [92 76 51 85]
 [45 26 32 94]
 [22 90 44 52]]

[92 85 94 90]

[50 18 42 92 76 26 32 94 22 90 44 52]

[50 18 42 51 45 26 32 22 44 52]


In [66]:
import numpy as np

a1 = np.random.randint(1, 10, 5)
s1 = np.sum(a1)

a2 = np.random.randint(1, 10, (3, 3))
s2 = np.sum(a2)

s2_ax0 = np.sum(a2, axis=0)
s2_ax1 = np.sum(a2, axis=1)

print(a1, a2, s2, s2_ax0, s2_ax1, sep='\n\n')

[7 3 7 5 4]

[[2 4 7]
 [2 2 8]
 [7 8 7]]

47

[11 14 22]

[13 12 22]


In [69]:
import numpy as np

a1 = np.random.randint(1, 10, 5)
cs1 = np.cumsum(a1)

a2 = np.random.randint(1, 10, (3, 3))
cs2 = np.cumsum(a2)

cs2_ax0 = np.cumsum(a2, axis=0)
cs2_ax1 = np.cumsum(a2, axis=1)

print(a1, cs1, a2, cs2, cs2_ax0, cs2_ax1, sep='\n\n')

[1 6 2 2 8]

[ 1  7  9 11 19]

[[8 2 6]
 [5 6 1]
 [6 2 8]]

[ 8 10 16 21 27 28 34 36 44]

[[ 8  2  6]
 [13  8  7]
 [19 10 15]]

[[ 8 10 16]
 [ 5 11 12]
 [ 6  8 16]]


In [10]:
import numpy as np

a1 = np.random.randint(1, 10, 5)
a1_mean = np.mean(a1)

a2 = np.random.randint(1, 10, (4, 4))
a2_mean = np.mean(a2)

a2_mean_ax0 = np.mean(a2, axis=0)
a2_mean_ax1 = np.mean(a2, axis=1)

print(a1, a1_mean, 
      a2, a2_mean, 
      a2_mean_ax0, a2_mean_ax1, sep='\n\n')

[4 6 1 2 3]

3.2

[[5 7 7 4]
 [4 8 3 3]
 [8 2 2 3]
 [4 8 4 9]]

5.0625

[5.25 6.25 4.   4.75]

[5.75 4.5  3.75 6.25]


In [9]:
import numpy as np

a1 = np.random.randint(1, 10, 5)
a1_min = np.min(a1)
a1_max = np.max(a1)

a2 = np.random.randint(1, 10, (4, 4))
a2_min = np.min(a2)
a2_max = np.max(a2)

a2_min_ax0 = np.min(a2, axis=0)
a2_max_ax1 = np.max(a2, axis=1)

print(a1, a1_min, a1_max, 
      a2, a2_min, a2_max, 
      a2_min_ax0, a2_max_ax1, sep='\n\n')

[3 6 4 5 4]

3

6

[[1 2 8 8]
 [7 1 3 6]
 [6 1 2 4]
 [2 5 8 5]]

1

8

[1 1 2 4]

[8 7 6 8]


In [3]:
import numpy as np

a1 = np.random.randint(1, 10, 5)
a1_sort = np.sort(a1)

a2 = np.random.randint(1, 10, (4, 4))
a2_sort_ax0 = np.sort(a2, axis=0)
a2_sort_ax1 = np.sort(a2, axis=1)

print(a1, a1_sort, 
      a2, a2_sort_ax0, a2_sort_ax1, 
      sep='\n\n')

[7 1 9 5 1]

[1 1 5 7 9]

[[8 2 9 9]
 [6 4 8 5]
 [9 9 6 4]
 [4 4 1 8]]

[[4 2 1 4]
 [6 4 6 5]
 [8 4 8 8]
 [9 9 9 9]]

[[2 8 9 9]
 [4 5 6 8]
 [4 6 9 9]
 [1 4 4 8]]


In [17]:
import numpy as np

a1 = np.random.choice([5, 10, 15, 20, 25, 30], 10)
a1_uq = np.unique(a1)

a2 = np.random.randint(1, 21, [4, 5])
a2_uq = np.unique(a2)

print(a1, a1_uq, 
      a2, a2_uq, sep='\n\n')

[30 30 30  5 10 15 15 10  5 30]

[ 5 10 15 30]

[[ 5  1 19 19  7]
 [12  9 12 19  5]
 [14 16  5  7 18]
 [14  1 18 10  4]]

[ 1  4  5  7  9 10 12 14 16 18 19]


In [23]:
import numpy as np

a1_1 = np.random.randint(10, 21, 5)
a1_2 = np.random.randint(1, 11, 4)

a1_concat = np.concatenate([a1_1, a1_2])

print(a1_1, a1_2, a1_concat, sep='\n\n')

[13 18 15 10 10]

[2 3 2 7]

[13 18 15 10 10  2  3  2  7]


In [29]:
import numpy as np

a2_1 = np.random.randint(1, 10, (2, 2))
a2_2 = np.random.choice([-3, -1.5, 0, 2.75, 3.141, 5.55], (2, 2))
a2_concat = np.concatenate([a2_1, a2_2])

print(a2_1, a2_2, a2_concat, sep='\n\n')

[[7 1]
 [3 8]]

[[0.   2.75]
 [2.75 5.55]]

[[7.   1.  ]
 [3.   8.  ]
 [0.   2.75]
 [2.75 5.55]]


In [35]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.choice([-10, -5, 0, 1, 3, 7], (2, 2))

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])

print(a, b, vstack, hstack, sep='\n\n')

[[8 2]
 [6 6]]

[[ 1 -5]
 [ 3 -5]]

[[ 8  2]
 [ 6  6]
 [ 1 -5]
 [ 3 -5]]

[[ 8  2  1 -5]
 [ 6  6  3 -5]]


In [42]:
import numpy as np

a = np.random.randint(1, 10, (2, 3))
v = a.view()

print(a, v, sep='\n\n', end='\n\n')

a[0] = 555
print(a, v, sep='\n\n')

[[6 8 7]
 [5 8 1]]

[[6 8 7]
 [5 8 1]]

[[555 555 555]
 [  5   8   1]]

[[555 555 555]
 [  5   8   1]]


In [47]:
import numpy as np

a = np.random.randint(1, 10, (2, 3))
c = a.copy()

print(a, c, sep='\n\n', end='\n\n')

a[0] = 555
print(a, c, sep='\n\n')

[[9 4 2]
 [4 6 9]]

[[9 4 2]
 [4 6 9]]

[[555 555 555]
 [  4   6   9]]

[[9 4 2]
 [4 6 9]]


In [25]:
import numpy as np

a1 = np.arange(1, 11) #.reshape([2, 5])
ar = np.reshape(a1, [2, 5])
print(ar, end='\n\n')
#ฟังก์ชัน arange(1, 11) จะได้อาร์เรย์มิติเดียว
#ที่มีจำนวนสมาชิก 10 ตัว แล้วใช้ reshape(2, 5)
#เพื่อเปลี่ยนเป็นอาร์เรย์ 2 มิติขนาด 2 x 5 หรือเขียนเป็น 
#ar = np.arange(1, 11).reshape([2, 5])

a2 = np.random.randint(1, 10, (2, 6))
b = np.reshape(a2, [3, 4])
print(a2, b, sep='\n\n', end='\n\n')

a2[0, 0] = 555
print(a2, b, sep='\n\n', end='\n\n')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[6 3 4 5 6 8]
 [4 5 6 1 3 3]]

[[6 3 4 5]
 [6 8 4 5]
 [6 1 3 3]]

[[555   3   4   5   6   8]
 [  4   5   6   1   3   3]]

[[555   3   4   5]
 [  6   8   4   5]
 [  6   1   3   3]]



In [20]:
import numpy as np

arr = np.arange(1, 13) 

a = np.reshape(arr, [2, -1])  #เทียบเท่า [2, 6]
b = np.reshape(arr, [4, -1])  #เทียบเท่า [4, 3]

c = np.reshape(arr, [-1, 3])  #เทียบเท่า [4, 3]
d = np.reshape(arr, [-1, 6])  #เทียบเท่า [2, 6]

print(a1, a, b, c, d, sep='\n\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
import numpy as np

a = np.random.randint(1, 10, (4, 3))
b = np.resize(a, [2, 6])
print(a, b, sep='\n\n', end='\n\n')

a[0,0] = 555
print(a, b, sep='\n\n', end='\n\n')

[[2 9 6]
 [4 2 8]
 [4 2 2]
 [1 8 1]]

[[2 9 6 4 2 8]
 [4 2 2 1 8 1]]

[[555   9   6]
 [  4   2   8]
 [  4   2   2]
 [  1   8   1]]

[[2 9 6 4 2 8]
 [4 2 2 1 8 1]]

